### ISSUE TITLE
Port-naming constraint doesn't work

### ISSUE THREAD

**Issue by lainra** [crcsmnky/gatekeeper-istio#1]
Hi @crcsmnky,

Thank you very much for the great demo at Kubecon. During the demo, there is one example that didn't work: The port naming convention constraint template.

I tried to debug it myself but my Rego skills are still too low to get it working properly.
Could you fix it or teach how to do it?

Cheers,

Raphael

**Comment by crcsmnky** [comment]
Can you provide some additional detail on what specifically didn't work? Were there errors with the `ConstraintTemplate` when you applied it? Or was it that the `Constraint` wasn't showing any violations in it's `status` field?

**Comment by crcsmnky** [comment]
Also any and all setup and sw version details would be helpful as well, just to know if there's a conflict in there I haven't seen yet.

**Comment by marshallford** [comment]
Perhaps unrelated, but I'm unable to get the port name constraint to work in the rego playground: https://play.openpolicyagent.org/p/f1wltAzb7g

**Comment by crcsmnky** [comment]
Hi @marshallford sorry for the late reply - I hadn't looked at this in awhile and finally found the issue you ran into.

[Line 28](https://github.com/crcsmnky/gatekeeper-istio/blob/master/templates/port-name-template.yaml#L28) of [port-naming-template.yaml](https://github.com/crcsmnky/gatekeeper-istio/blob/master/templates/port-name-template.yaml) causes the issue you saw in the Rego Playground.

This code has an issue when running in the Rego playground - `service.metadata.namespace` hasn't been set and causes the `violation` to evaluate to `false`.
```
msg := sprintf("service %v.%v port name missing prefix", 
  [service.metadata.name, service.metadata.namespace])
```

Easiest fix was to change to something like:
```
msg := "service port name missing prefix"
```

Which also makes life easier when writing unit tests outside of a running Kubernetes cluster.

**Comment by crcsmnky** [comment]
Closing this original issue for now, since it hasn't been updated.
